a:hover{
    color:none !important;
}
.bodyBg{
    background: <?php echo  $sm['landing']['background_color']['val']; ?>;
    color: <?php echo  $sm['landing']['font_color']['val']; ?>;
}
.headerStyle{
    background: <?php echo  $sm['landing']['header_bg']['val']; ?>;
}
#header a {
    color: <?php echo  $sm['landing']['header_color']['val']; ?> !important;
    font-family: '<?php echo  $sm['landing']['header_font']['val']; ?>' !important;
    font-size: <?php echo  $sm['landing']['header_fontSize']['val']; ?>px !important;
}
#header li {
    color: <?php echo  $sm['landing']['header_color']['val']; ?> !important;
    font-family: '<?php echo  $sm['landing']['header_font']['val']; ?>' !important;
    font-size: <?php echo  $sm['landing']['header_fontSize']['val']; ?>px !important;
}

.login-section-title{
    color: <?php echo  $sm['landing']['header_main_text_font_color']['val']; ?> !important;
    font-family: '<?php echo  $sm['landing']['header_main_text_font']['val']; ?>' !important;
    font-size: <?php echo  $sm['landing']['header_main_text_fontSize']['val']; ?>px !important;
    line-height: <?php echo  $sm['landing']['header_main_text_fontSize']['val']; ?>px;
    font-weight:bold;
}

.loginbox-tabset .log-tabs{
    background: <?php echo  $sm['landing']['form_bg']['val']; ?> !important;
    color: <?php echo  $sm['landing']['form_font_color']['val']; ?> !important;
    font-family: '<?php echo  $sm['landing']['form_font']['val']; ?>' !important;
    font-size: <?php echo  $sm['landing']['form_fontSize']['val']; ?>px !important;
    padding:10px; 
}
.loginbox-tab-container{
    background: <?php echo  $sm['landing']['form_bg']['val']; ?> !important;

}
.form-control{
    background: <?php echo  $sm['landing']['form_input_bg']['val']; ?> !important;
    border:none;
    box-shadow:none;  
    border-radius:<?php echo  $sm['landing']['form_input_border']['val']; ?>px;
    padding:12px;
}
.form-control input{
    color: <?php echo  $sm['landing']['form_input_color']['val']; ?> !important;
    font-family: '<?php echo  $sm['landing']['form_font']['val']; ?>' !important;
    font-size: <?php echo  $sm['landing']['form_fontSize']['val']; ?>px !important;
}
.form-control select{
    color: <?php echo  $sm['landing']['form_input_color']['val']; ?> !important;
    font-family: '<?php echo  $sm['landing']['form_font']['val']; ?>' !important;
    font-size: <?php echo  $sm['landing']['form_fontSize']['val']; ?>px !important;
}
.loginbox-note{
    color: <?php echo  $sm['landing']['form_input_color']['val']; ?> !important;
    font-family: '<?php echo  $sm['landing']['form_font']['val']; ?>' !important;
    font-size: <?php echo  $sm['landing']['form_fontSize']['val']/1.4; ?>px !important;
}
.user-recovery-pass{
    color: <?php echo  $sm['landing']['form_input_color']['val']; ?> !important;
    font-family: '<?php echo  $sm['landing']['form_font']['val']; ?>' !important;
    font-size: <?php echo  $sm['landing']['form_fontSize']['val']/1.2; ?>px !important;
}

.log-btn{
    background: <?php echo  $sm['landing']['form_btn_bg']['val']; ?> !important;
    color: <?php echo  $sm['landing']['form_btn_color']['val']; ?> !important;
    font-family: '<?php echo  $sm['landing']['form_font']['val']; ?>' !important;
    font-size: <?php echo  $sm['landing']['form_fontSize']['val']*1.1; ?>px !important;
    height:40px !important; 
    border-radius:<?php echo  $sm['landing']['form_btn_border']['val']; ?>px;
}

.stats-value-box{
    font-family: '<?php echo  $sm['landing']['content_header_font']['val']; ?>' !important;
    font-size: <?php echo  $sm['landing']['content_header_fontSize']['val']; ?>px !important;
    color: <?php echo  $sm['landing']['content_header_fontColor']['val']; ?> !important;
    line-height: <?php echo  $sm['landing']['content_header_fontSize']['val']; ?>px !important;
    padding:10px 40px 10px 40px;  
}

.heading{
    font-family: '<?php echo  $sm['landing']['content_header_font']['val']; ?>' !important;
    font-size: <?php echo  $sm['landing']['content_header_fontSize']['val']; ?>px !important;
    line-height: <?php echo  $sm['landing']['content_header_fontSize']['val']; ?>px !important;
}

.subheading{
    font-family: '<?php echo  $sm['landing']['content_header_font']['val']; ?>' !important;
    font-size: <?php echo  $sm['landing']['content_header_fontSize']['val']*0.8; ?>px !important;
    color: <?php echo  $sm['landing']['content_header_fontColor']['val']; ?> !important;
    line-height: <?php echo  $sm['landing']['content_header_fontSize']['val']*0.8; ?>px !important;
}

.description p{
    font-family: '<?php echo  $sm['landing']['content_font']['val']; ?>' !important;
    font-size: <?php echo  $sm['landing']['content_fontSize']['val']*0.9; ?>px !important;
    color: <?php echo  $sm['landing']['content_fontColor']['val']; ?> !important;
    line-height: <?php echo  $sm['landing']['content_fontSize']['val']; ?>px !important;
}

.stats-section-intro p{
    font-family: '<?php echo  $sm['landing']['content_font']['val']; ?>' !important;
    font-size: <?php echo  $sm['landing']['content_fontSize']['val']; ?>px !important;
    color: <?php echo  $sm['landing']['content_fontColor']['val']; ?> !important;
    line-height: <?php echo  $sm['landing']['content_fontSize']['val']; ?>px !important;
}

.stats-title{
    font-family: '<?php echo  $sm['landing']['content_font']['val']; ?>' !important;
    font-size: <?php echo  $sm['landing']['content_fontSize']['val']; ?>px !important;
    color: <?php echo  $sm['landing']['content_fontColor']['val']; ?> !important;
    line-height: <?php echo  $sm['landing']['content_fontSize']['val']; ?>px !important;
}

.footer-nav li a{
    font-family: '<?php echo  $sm['landing']['content_font']['val']; ?>' !important;
    font-size: <?php echo  $sm['landing']['content_fontSize']['val']*0.8; ?>px !important;
    line-height: <?php echo  $sm['landing']['content_fontSize']['val']; ?>px !important;
    color: <?php echo  $sm['landing']['content_footer_color']['val']; ?> !important;
}